# Generated by Django 4.1 on 2022-08-19 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 20, 15, 3, 74515, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
